### ISSUE TITLE
Tasks of "Someday" projects appear in the "Next" column

### ISSUE THREAD

**Issue by nilsberg** [AlexanderWillner/KanbanView#3]
Hi,
in the "Next" column of the Kanban view, the tasks of projects that are scheduled for "Someday" appear. The tasks themselves are not scheduled for "Someday", however Things treats them as such (when they are not scheduled for a specific day).

edit: Tasks of upcoming projects are also shown in "Next".

**Comment by AlexanderWillner** [comment]
Thanks. Will check.

**Comment by nilsberg** [comment]
Similar problem: MIT tasks do not appear in the MIT column, when they are scheduled for today. Though this might also be feature, depending on your preferences. For me, MIT tasks, that are not Upcoming or Someday (or their parent projects) should always appear in the MIT column.

**Comment by AlexanderWillner** [comment]
Thanks for the feedback. I've refactored the queries a lot to make sure they are more consistent. I think your first two issues should be fixed now. Regarding the, `MIT` and `Waiting` tasks, it might make sense to show them regardless of the status of their parent projects. Open to discussions though.

**Comment by nilsberg** [comment]
> Thanks for the feedback

Thank you for making the app!

>I think your first two issues should be fixed now. 

Almost. From what I see, tasks that are under a heading in a Someday/Upcoming project still appear in the Next column.

>Regarding the, `MIT` and `Waiting` tasks, it might make sense to show them regardless of the status of their parent projects.

I agree. And I confirm that the `MIT` tasks are now shown in the MIT column even when scheduled for today.

**Comment by nilsberg** [comment]
Thank you

**Comment by AlexanderWillner** [comment]
Your change request didn't work as expected. I looked at the database again and hope the new changes reflect the situation better. Please test.

**Comment by nilsberg** [comment]
I realized this when running the tests (too late, I am sorry), then saw your changes, tested them (with my tasks) and then closed the issue ;)
It still works for me. You can now close the issue.
